### ISSUE TITLE
小便器スタンプの両サイドの余白をわかるようにして、少なくしてほしい

### ISSUE THREAD

**Issue by takahide0413** [Aciryl/EasyCAD_Support#19]
小便器のすぐ横にスクリーンが付くことが多いので、どこまでがスタンプかわからないと、ぎりぎりにスクリーンを設置できないので分かるようにしてほしい。なるべく余白を小さくしてもらえると設置しやすい。

**Comment by Aciryl** [comment]
両側に線を引くのと、小便器を四角で囲むのでは、どちらがいいですか？

**Comment by Aciryl** [comment]
分かりました
追加しておきます

**Comment by Aciryl** [comment]
追加しました
両サイドの余白は「Xサイズ」を変更すると、調整できます。
次のバージョンから適用されます
